.TH YED-SAVE_LAYOUT 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
save_layout \- Saves the layout of the current frame / buffer configuration to a file.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
save_layout, frame, special, buffers, layout
